# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IugoAi < Formula
  desc "Gentle-AI — Ecosystem, Frameworks, Workflows for AI coding agents."
  homepage "https://github.com/iugo-programming/iugo-ai"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iugo-programming/iugo-ai/releases/download/v1.0.1/iugo-ai_1.0.1_darwin_amd64.tar.gz"
      sha256 "7b26800d6f76c35ca1617b9b2c6ad4b8ef55a5400710c70b919a155518b69f4d"

      define_method(:install) do
        bin.install "iugo-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iugo-programming/iugo-ai/releases/download/v1.0.1/iugo-ai_1.0.1_darwin_arm64.tar.gz"
      sha256 "70013eafa4fbb2796c4db5dd672a8c2a222dc3b06a823b71f5fa38ee21fd63f0"

      define_method(:install) do
        bin.install "iugo-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iugo-programming/iugo-ai/releases/download/v1.0.1/iugo-ai_1.0.1_linux_amd64.tar.gz"
      sha256 "83478ce1ccd2a06eeeae6b2a17bde28829f112a4993ff2aba0051d059d7351cf"
      define_method(:install) do
        bin.install "iugo-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iugo-programming/iugo-ai/releases/download/v1.0.1/iugo-ai_1.0.1_linux_arm64.tar.gz"
      sha256 "5c230410015cf53f82eec49b7b2e29353c0738ddbc42cc52180eae23e0dcd3af"
      define_method(:install) do
        bin.install "iugo-ai"
      end
    end
  end
end
