# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IugoAi < Formula
  desc "Gentle-AI — Ecosystem, Frameworks, Workflows for AI coding agents."
  homepage "https://github.com/iugo-programming/iugo-ai"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iugo-programming/iugo-ai/releases/download/v1.0.0/iugo-ai_1.0.0_darwin_amd64.tar.gz"
      sha256 "18e3aee283a18f759eedd6cdc4be280cabadd0ec2e75914d559b6b10ff7ffb93"

      define_method(:install) do
        bin.install "iugo-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iugo-programming/iugo-ai/releases/download/v1.0.0/iugo-ai_1.0.0_darwin_arm64.tar.gz"
      sha256 "e5287df96d154ce8c843dcba1fafde0d0a450f3842647fab0f622801d1b4c61e"

      define_method(:install) do
        bin.install "iugo-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iugo-programming/iugo-ai/releases/download/v1.0.0/iugo-ai_1.0.0_linux_amd64.tar.gz"
      sha256 "7aef7d1a26757c7ac6dbb86b0b3f8c0fd16db7308494bc1d6775ea4ed6176fad"
      define_method(:install) do
        bin.install "iugo-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iugo-programming/iugo-ai/releases/download/v1.0.0/iugo-ai_1.0.0_linux_arm64.tar.gz"
      sha256 "791c2e6edaf7ed411c19f16836c9ae51af173e7807830f2c8492f0a1befc3a87"
      define_method(:install) do
        bin.install "iugo-ai"
      end
    end
  end
end
